#image: 'ruby:2.3.4'

services:
#  - redis:latest
#  - desofto/postgres:ramdisk
#  - postgres:9.3
#  - andir/postgresql-tmpfs:latest

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - vendor/ruby

#before_script:
#  - apt update -y && apt install openssh-client -y
#  - eval $(ssh-agent -s)
#  - ssh-add <(echo "$SSH_PRIVATE_KEY")
#  - mkdir -p ~/.ssh
#  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - cops
#  - tests
#  - deploy

rubocop:
  stage: cops
  script:
    - apt-get update -q && apt-get install nodejs -yqq
    - gem install bundler  --no-ri --no-rdoc
    - bundle install --path vendor
    - rubocop -R

brakeman:
  stage: cops
  script:
    - gem install brakeman --no-ri --no-rdoc
    - export LC_CTYPE="C.UTF-8"
    - brakeman -z -w2

# bundle-audit:
#   stage: cops
#   script:
#     - gem install bundler-audit  --no-ri --no-rdoc
#     - bundle-audit update
#     - bundle-audit check

#rspec:
#  stage: tests
#  script:
#    - apt-get update -q && apt-get install nodejs -yqq
#    - gem install bundler  --no-ri --no-rdoc
#    - bundle install --path vendor
#    - mv config/database.ci.yml config/database.yml
#    - bundle exec rake db:create db:schema:load --trace
#    - bundle exec rails db:environment:set
#    - bundle exec rake parallel:create
#    - bundle exec rake i18n:js:export
#    - bundle exec parallel_rspec --runtime-log ./parallel_runtime_rspec.log spec || true
#    - unset CIRCLECI
#    - bundle exec rspec --only-failure
#  artifacts:
#    paths:
#      - coverage/
#      - tmp/quick_rspec.new.json
#    expire_in: 7 days

#sync_to_gitlab:
#  stage: deploy
#  only:
#    - master
#  script:
#    - ssh-add <(echo "$SSH_PRIVATE_KEY_GITLAB")
#    - git checkout master
#    - git pull origin master -f
#    - git remote remove gitlab || true
#    - git remote add gitlab git@gitlab.com:MercuryTC/mercury.git
#    - git push gitlab master -f

#deploy_staging:
#  stage: deploy
#  script:
#    - bundle install --path vendor
#    - current=`git rev-parse HEAD`
#    - cap staging deploy REVISION=$current
#  environment:
#    name: staging
#    url: https://staging.mercurytc.com
#  only:
#    - master

#deploy_production:
#  stage: deploy
#  script:
#    - bundle install --path vendor
#    - current=`git rev-parse HEAD`
#    - cap production deploy REVISION=$current
#  environment:
#    name: production
#    url: https://production.mercurytc.com
#  only:
#    - master
